### ISSUE TITLE
Sample data 

### ISSUE THREAD

**Issue by akhileshkumargangwar** [sesenosannko/dcnn_textvae#3]
Hi, 
           May u please include some sample data  and generated sentence. Please show the result in your blog and generated texts. 
           How to generate sentence according to sentiment like explained in research  paper

**Comment by ryokamoi** [comment]
Thank you for your comment.
I will fix the blog url soon.

However, please wait a little for sample data.
I'm sorry but this is not an ongoing project.
I'm going to modify this repository, but I cannot say when it will be.

My apologies. Thank you for your patience.

**Comment by akhileshkumargangwar** [comment]
Thanks for your kind reply!
